### ISSUE TITLE
Not working with php7?

### ISSUE THREAD

**Issue by nitinsbuzz** [mkoppanen/php-zbarcode#22]
Could you update this extension and the imagick extension to work with php7?

**Comment by jorissteyn** [comment]
Hi!

Imagick has already been [ported to php7](https://github.com/mkoppanen/imagick/tree/phpseven) but it's not yet merged into the mainline (I don't know why not).

I'm currently working on porting zbarcode to php7, you can see my progress here: https://github.com/jorissteyn/php-zbarcode/commits/gophp7. It's almost finished, [all tests are passing](https://travis-ci.org/jorissteyn/php-zbarcode/builds/138751647), except the one that uses imagick because imagick no longer exposes the internals that zbarcode needs (see https://github.com/mkoppanen/php-zbarcode/issues/21).

**Comment by jorissteyn** [comment]
Status update:

 - I had my gophp7 branch of zbarcode reviewed by a core developer and fixed all wrongs (all tests now pass with valgrind enabled)
 - Still working on a solution for the Imagick integration: https://github.com/mkoppanen/imagick/issues/169

**Comment by cyril2000** [comment]
Hi!
I've been using your great php-library (wrapper) for a document archiving solution for a few years now and would love to update my system to php7. I am also using the imagick part. My last test to compile it with php7 a few months ago didn't work. Has the problem been solved in between?
Thanks for your great work!

**Comment by psaikali** [comment]
Hey there,

Trying to install ZBarCode (from @jorissteyn repo / gophp7 branch) but I get this error on `./configure`:

`checking ImageMagick MagickWand API configuration program... configure: error: not found. Please provide a path to MagickWand-config or Wand-config program.`

What's the solution :/ ?

Thanks !

**Comment by psaikali** [comment]
For info my `phpinfo()` looks like that http://media.mosaika.fr/kYT6

The funny thing is that I successfully installed zbarcode on PHP7 on my local Vagrant environment a couple of weeks ago.
I'm on my prod server now but can't figure out the way I did it :/ Maybe it's because I'm using Plesk running a couple of PHP versions ?

Help greatly appreciated,

Thanks for your help and work.

**Comment by psaikali** [comment]
My bad, I did find a way to compile it.

But I get this error now :
`"Module compiled with module API=20151012"`
`"PHP    compiled with module API=20160303"`

Any way to make it work with PHP 7.1 ?

Cheers !
